import '@/app/globals.css'
import { Toaster } from '@/components/ui/toaster'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import localFont from 'next/font/local'

// const myFont = localFont({src: '../../font/BADABB.ttf'})

const inter = Inter({ subsets: ['latin'], })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  viewport: 'width=device-width, initial-scale=1',

}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={`tracking-wider`}>
      <body className={inter.className}>
        {children}
        {/* <Toaster /> */}
      </body>
    </html>
  )
}